### ISSUE TITLE
Twitter and Instagram plugins issues (not able to run wizzard)

### ISSUE THREAD

**Issue by amincewicz** [jkakavas/creepy#11]
Hello,
I can't configurate the plugins. For Instagram it gives me an error saying that I should check if the link I pasted as token is correct. For Twitter it says we are unable to access token for your account. How do I fix these two?

**Comment by jkakavas** [comment]
Which version ? Windows / Linux / OSX  ?

**Comment by amincewicz** [comment]
Windows

**Comment by jkakavas** [comment]
Which version ?

**Comment by amincewicz** [comment]
It is the newest one v1.3. I downloaded it like 20min ago.

**Comment by jkakavas** [comment]
ok send me the log files you can find in C:\Users\YOUR_USERNAME\.creepy so that I can take a look

**Comment by amincewicz** [comment]
I just sent you an email with the file. Thank you!

**Comment by jkakavas** [comment]
I can see lines like this 
In twitter.py:128: [Errno 13] Permission denied: u'C:\\Program Files\\creepy\\plugins\\twitter\\twitter.conf'

This means that you overwrote the default installation directory ( which is your home folder ) . creepy does not have permissions to read/write in your Program Files folder - and shouldn't have -. 

I suggest that you reinstall creepy somewhere your current user account has read / write permissions.

**Comment by amincewicz** [comment]
Thank you very much. I will fix it right away

**Comment by amincewicz** [comment]
It works now. Thank you very much!

**Comment by jkakavas** [comment]
No worries, enjoy !
