### ISSUE TITLE
No locations found for the selected project

### ISSUE THREAD

**Issue by CharleyM** [jkakavas/creepy#14]
Hi,
I'm new here please be tolerant :)
I installed creepy on windows and mac environment and both give me the same result: "No locations found for the selected project".

Configuration wizard is ok for the plugins I need.
Project wizard doesn't gives me any errors.

Did I do something wrong?

Thanks for the help!
Have a nice day!

**Comment by jkakavas** [comment]
Hi
Probably the accounts you select to "target" had no geolocation information in their tweets/images.

**Comment by CharleyM** [comment]
Hi,
Thanks for the quick reaction.
Actually it does have... because I found them with another tool based on geolocation :(

**Comment by jkakavas** [comment]
Interesting. You can either share the account details with me so I can run
and see what I get, or you can test with my instagram account
(ilektrojohn), you should find 35 locations.


2015-08-03 12:44 GMT+03:00 CharleyM <notifications@github.com>:

**Comment by CharleyM** [comment]
Hi,I tested it with your account and still gets no results... I find your account in the wizard but it doesn't give any results/locations at the end. Is there some restriction based on country or other parameter?Thanks! 


     On Monday, August 3, 2015 9:50 AM, Ioannis Kakavas <notifications@github.com> wrote:
   

 Interesting. You can either share the account details with me so I can run
and see what I get, or you can test with my instagram account
(ilektrojohn), you should find 35 locations.


2015-08-03 12:44 GMT+03:00 CharleyM <notifications@github.com>:

**Comment by jkakavas** [comment]
No, no restriction. When you click at the "Test plugin configuration"
button for instagram in the Plugins configuration page, what do you get ?
Also, send me the log files you can find in .creepy directory in your home
folder.

2015-08-03 13:07 GMT+03:00 CharleyM <notifications@github.com>:

> Hi,I tested it with your account and still gets no results... I find your
> account in the wizard but it doesn't give any results/locations at the end.
> Is there some restriction based on country or other parameter?Thanks!
>
>
> On Monday, August 3, 2015 9:50 AM, Ioannis Kakavas <

**Comment by CharleyM** [comment]
Hep, i'm not that familiar with such files... what do you mean with the log files? what kind of file am I suppose to find and send? Thanks !

**Comment by jkakavas** [comment]
answer my question about the
" When you click at the "Test plugin configuration" button for instagram in
the Plugins configuration page, what do you get ?"

and if that does not help, I will explain which logs I need

2015-08-03 13:24 GMT+03:00 CharleyM <notifications@github.com>:

**Comment by CharleyM** [comment]
Yes sorry it was because it said "Instagram plugin is correctly configured"...

**Comment by jkakavas** [comment]
Ok, there is a folder named .creepy ( mind the dot (.) in the beginning. If
you are on windows, its in  C:\Users\yourusername\.creepy if you are on
Linux/OSX it's in /home/yourusername/.creepy .

Inside this there are some log files, please make a .tar or .zip archive
out of them and send them to my mail because you can not attach it here

2015-08-03 13:30 GMT+03:00 CharleyM <notifications@github.com>:

**Comment by navegan** [comment]
Hi, 
I would like to report the same problem when i try to get info.
I've tried with user (ilektrojohn) and here i send you the log file......

DEBUG:2015-08-05 08:06:57,359  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-08-05 08:07:07,859  In twitter.py:49: Searching for Targets from Twitter Plugin. Search term is : ilektrojohn
DEBUG:2015-08-05 08:07:08,282  In twitter.py:55: Twitter returned  1 results
DEBUG:2015-08-05 08:07:27,066  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-08-05 08:07:27,066  In twitter.py:200: Attempting to retrieve profile information for 15109211
DEBUG:2015-08-05 08:07:27,380  In twitter.py:228: Attempting to retrieve the tweets for user 15109211
ERROR:2015-08-05 08:08:23,934  In twitter.py:345: {"errors":[{"message":"Rate limit exceeded","code":88}]}
ERROR:2015-08-05 08:08:23,934  In twitter.py:346: Error getting locations from twitter plugin

**Comment by jkakavas** [comment]
Hi @navegan 
1) The log lines you share with me show that you searched for my twitter account (which has no geotagged tweets ), I asked CharleyM to test my instagram account, not the twitter one. 

2) You''ve hit twitter's rate limits. See here for more details https://dev.twitter.com/rest/public/rate-limiting

**Comment by navegan** [comment]
Oh, I'm sorry. I'm going to try with another user (for example me)... :-)
Thank you

**Comment by jkakavas** [comment]
This won't help with twitter. The fact that you ve already hit the rate limits, means that you will have to wait for the current window ( 60 mins ) to end, before you are granted more requests.

**Comment by Sagar1905** [comment]
No Location found!
DEBUG:2016-02-29 02:31:51,838  In CreepyMain.py:576: Attempting to draw locations for the current project

**Comment by jkakavas** [comment]
Open a new ticket, don't hijack other (and especially closed) ones.
