### ISSUE TITLE
Cannot run on Arch Linux

### ISSUE THREAD

**Issue by hamlinux** [jkakavas/creepy#15]
Running python 3.4.3 and python-pyqt4
cloned from latest github
dependencies installed via pip

Running 'python CreepyMain.py' yields

  File "CreepyMain.py", line 192
    except Exception, err:
                    ^
SyntaxError: invalid syntax

**Comment by hamlinux** [comment]
Also I have tried this on 32-bit and 64-bit architectures with the same results.
kernel 4.0.7-2-ARCH

Thanks

**Comment by jkakavas** [comment]
Never tried it with Python 3, I think there are certain things to be fixed
before that can work.

Check instructions for Linux on www.geocreepy.com and please try running it
with Python 2.7

**Comment by hamlinux** [comment]
Am Running everything in 2.7 now but get 
python2 CreepyMain.py
Traceback (most recent call last):
  File "CreepyMain.py", line 18, in <module>
    from dominate import document
ImportError: No module named dominate

Do you know if 1.3 will be the default version in the new Kali release?

**Comment by jkakavas** [comment]
Assuming you followed the rest of the instructions,

pip install dominate

Should fix this problem. I'll update the instructions too, thanks!

No idea about kali unfortunately :/
