### ISSUE TITLE
Google and Twitter plugin fails

### ISSUE THREAD

**Issue by lxtrvn** [jkakavas/creepy#20]
I am running creepy on linux i386 , and I cannot get the wizard tool to configure twitter and google plugins. The instagram works fine, and i have not attempted flicker. 
here is the stderr log
-----------------------
DEBUG:yapsy_loaded_plugin_Flickr_Plugin_0:Trying to load the labels file for the  flickr plugin .
DEBUG:yapsy_loaded_plugin_Instagram_Plugin_0:Trying to load the labels file for the  instagram plugin .
DEBUG:yapsy_loaded_plugin_Twitter_Plugin_0:Trying to load the labels file for the  twitter plugin .
DEBUG:yapsy_loaded_plugin_GooglePlus_Plugin_0:Trying to load the labels file for the  googleplus plugin .
ERROR:yapsy_loaded_plugin_GooglePlus_Plugin_0:No JSON object could be decoded
ERROR:yapsy_loaded_plugin_GooglePlus_Plugin_0:'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/components/PluginsConfigurationDialog.py", line 38, in checkPluginConfiguration
    checkPluginConfigurationResultDialog.ui.checkPluginConfigurationResultLabel.setText(plugin.name + self.trUtf8(' is not correctly configured.') + isConfigured[1])
TypeError: unsupported operand type(s) for +: 'QString' and 'exceptions.AttributeError'
ERROR:yapsy_loaded_plugin_GooglePlus_Plugin_0:No JSON object could be decoded
ERROR:yapsy_loaded_plugin_GooglePlus_Plugin_0:'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/components/PluginsConfigurationDialog.py", line 38, in checkPluginConfiguration
    checkPluginConfigurationResultDialog.ui.checkPluginConfigurationResultLabel.setText(plugin.name + self.trUtf8(' is not correctly configured.') + isConfigured[1])
TypeError: unsupported operand type(s) for +: 'QString' and 'exceptions.AttributeError'
ERROR:yapsy_loaded_plugin_Twitter_Plugin_0:Error authenticating with Twitter API.
ERROR:yapsy_loaded_plugin_Twitter_Plugin_0:[{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
ERROR:yapsy_loaded_plugin_Twitter_Plugin_0:'OAuthHandler' object has no attribute 'access_token_secret'
DEBUG:yapsy_loaded_plugin_Flickr_Plugin_1:Trying to load the labels file for the  flickr plugin .
DEBUG:yapsy_loaded_plugin_Instagram_Plugin_1:Trying to load the labels file for the  instagram plugin .
DEBUG:yapsy_loaded_plugin_Twitter_Plugin_1:Trying to load the labels file for the  twitter plugin .
DEBUG:yapsy_loaded_plugin_GooglePlus_Plugin_1:Trying to load the labels file for the  googleplus plugin .

--------------------------------------

here is main log
-----------------
DEBUG:2015-10-11 22:46:10,429  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-11 22:46:10,526  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-11 22:46:10,631  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-11 22:46:11,872  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-11 22:46:27,567  In twitter.py:178: Error authenticating with Twitter API.
ERROR:2015-10-11 22:46:27,567  In twitter.py:179: [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
DEBUG:2015-10-11 22:46:34,828  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-11 22:46:34,830  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-11 22:46:34,831  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-11 22:46:34,833  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:32:58,858  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:32:58,880  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:32:58,893  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:32:59,861  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:33:03,418  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:33:03,419  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:33:03,420  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:33:03,422  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:33:37,641  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 00:33:42,721  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:33:42,723  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:33:42,724  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:33:42,726  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:34:00,421  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:34:00,423  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:34:00,424  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:34:00,428  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:34:03,465  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 00:34:03,465  In googleplus.py:164: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
ERROR:2015-10-12 00:34:05,960  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 00:34:05,960  In googleplus.py:164: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
DEBUG:2015-10-12 00:34:15,878  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:34:15,879  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:34:15,880  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:34:15,882  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:35:18,984  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:35:18,985  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:35:18,988  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:35:18,990  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:38:22,178  In twitter.py:128: 'OAuthHandler' object has no attribute 'access_token_secret'
DEBUG:2015-10-12 00:38:23,792  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:38:23,793  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:38:23,795  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:38:23,797  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:38:51,231  In twitter.py:128: 'OAuthHandler' object has no attribute 'access_token_secret'
DEBUG:2015-10-12 00:38:54,562  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:38:54,563  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:38:54,565  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:38:54,567  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:39:37,452  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 00:39:39,773  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:39:39,774  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:39:39,776  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:39:39,778  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:39:50,754  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:39:50,755  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:39:50,757  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:39:50,758  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:40:02,385  In twitter.py:49: Searching for Targets from Twitter Plugin. Search term is : lxtrvn
ERROR:2015-10-12 00:40:02,790  In twitter.py:72: [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
ERROR:2015-10-12 00:40:02,791  In twitter.py:73: Error searching for targets in Twitter plugin.
ERROR:2015-10-12 00:40:02,791  In flickr.py:54: 'module' object has no attribute 'auth'
ERROR:2015-10-12 00:40:02,791  In flickr.py:73: 'NoneType' object has no attribute 'people_findByUsername'
DEBUG:2015-10-12 00:40:02,792  In flickr.py:76: 0 possible targets were found matching the search query
DEBUG:2015-10-12 00:40:02,792  In googleplus.py:49: Searching for Targets from Google+ Plugin. Search term is : lxtrvn
ERROR:2015-10-12 00:40:02,792  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 00:40:02,792  In googleplus.py:72: 'NoneType' object has no attribute 'people'
ERROR:2015-10-12 00:40:02,792  In googleplus.py:73: Error searching for targets in Google+ plugin.
DEBUG:2015-10-12 00:40:02,792  In instagram.py:54: Attempting to search for targets. Search term was : lxtrvn
DEBUG:2015-10-12 00:40:03,692  In instagram.py:73: 1 possible targets were found matching the search query
DEBUG:2015-10-12 00:40:03,705  In twitter.py:49: Searching for Targets from Twitter Plugin. Search term is : lxtrvn
ERROR:2015-10-12 00:40:04,107  In twitter.py:72: [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
ERROR:2015-10-12 00:40:04,107  In twitter.py:73: Error searching for targets in Twitter plugin.
ERROR:2015-10-12 00:40:04,108  In flickr.py:54: 'module' object has no attribute 'auth'
ERROR:2015-10-12 00:40:04,108  In flickr.py:73: 'NoneType' object has no attribute 'people_findByUsername'
DEBUG:2015-10-12 00:40:04,108  In flickr.py:76: 0 possible targets were found matching the search query
DEBUG:2015-10-12 00:40:04,109  In googleplus.py:49: Searching for Targets from Google+ Plugin. Search term is : lxtrvn
ERROR:2015-10-12 00:40:04,109  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 00:40:04,109  In googleplus.py:72: 'NoneType' object has no attribute 'people'
ERROR:2015-10-12 00:40:04,109  In googleplus.py:73: Error searching for targets in Google+ plugin.
DEBUG:2015-10-12 00:40:04,109  In instagram.py:54: Attempting to search for targets. Search term was : lxtrvn
DEBUG:2015-10-12 00:40:05,106  In instagram.py:73: 1 possible targets were found matching the search query
DEBUG:2015-10-12 00:50:32,009  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:50:32,324  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:50:32,415  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:50:34,171  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:50:44,083  In twitter.py:178: Error authenticating with Twitter API.
ERROR:2015-10-12 00:50:44,083  In twitter.py:179: [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
ERROR:2015-10-12 00:51:02,737  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 00:51:02,737  In googleplus.py:164: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
DEBUG:2015-10-12 00:51:12,205  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:51:12,207  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:51:12,209  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:51:12,210  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:53:01,847  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 00:53:05,963  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:53:05,964  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:53:05,966  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:53:05,968  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:54:26,015  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 00:54:27,068  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:54:27,070  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:54:27,072  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:54:27,073  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:54:50,647  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:54:50,649  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:54:50,650  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:54:50,652  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:55:05,782  In instagram.py:54: Attempting to search for targets. Search term was : irie genetics
DEBUG:2015-10-12 00:55:06,656  In instagram.py:73: 1 possible targets were found matching the search query
DEBUG:2015-10-12 00:55:36,052  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:55:36,054  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:55:36,055  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:55:36,057  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 00:57:49,836  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:57:49,856  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:57:49,865  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:57:50,826  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 00:58:18,123  In twitter.py:128: 'OAuthHandler' object has no attribute 'access_token_secret'
DEBUG:2015-10-12 00:58:19,181  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 00:58:19,182  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 00:58:19,185  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 00:58:19,187  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 01:02:00,811  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 01:02:00,831  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 01:02:00,844  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 01:02:01,799  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 01:02:29,107  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 01:02:29,107  In googleplus.py:164: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
ERROR:2015-10-12 01:02:30,578  In googleplus.py:86: No JSON object could be decoded
ERROR:2015-10-12 01:02:30,578  In googleplus.py:164: 'NoneType' object has no attribute 'people'
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'
ERROR:2015-10-12 01:02:34,408  In twitter.py:178: Error authenticating with Twitter API.
ERROR:2015-10-12 01:02:34,409  In twitter.py:179: [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
ERROR:2015-10-12 01:03:08,182  In twitter.py:128: 'OAuthHandler' object has no attribute 'access_token_secret'
DEBUG:2015-10-12 01:03:11,730  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 01:03:11,731  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 01:03:11,733  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 01:03:11,737  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
--------------------------------------------------------

**Comment by jkakavas** [comment]
Hi there, thanks for your report

Have you followed the instructions below ?
```
 apt-get install python-qt4 
 pip install pytz python-qt flickrapi python-instagram yapsy tweepy google-api-python-client python-dateutil configobj dominate
```

**Comment by lxtrvn** [comment]
yes. python-qt4 is already newest version, and the pip install shows already satisfied.  could the problem be in the directory path where the git cloned to? I used home/.

**Comment by lxtrvn** [comment]
And if it matters, i apt-get purged creepy from Kali 2.0 and reinstalled using your sites instructions...

**Comment by jkakavas** [comment]
That's the correct approach, at least until we bring the Kali package up to date. Can you please check ```
find / -iname 'twitter.conf'
```
or
```
find / -iname 'googleplus.conf'
```
return only one result ? It kind of looks like that there are some old configuration files left in from the kali installation. It looks like it either can't read the configuration file, or it reads an incomplete version of them. Also, make sure that you run creepy with a user that has read access to the folder that creepy is installed in 

 Otherwise, in line 138 of googleplus.py, and line 179 of twitter.py please change
```
logger.error(err)
```
to
```
logger.exception(err)
```
so that we can see the stack trace

**Comment by lxtrvn** [comment]
the find query resulted in there being two config files. i removed the one that wasnt supposed to be there. that fixed the twitter wizard, however the google wizard still doesnt work. i changed  the error line in the .py file ad here is the recent entries to the main log .  
--
DEBUG:2015-10-12 11:17:26,776  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:17:26,918  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:17:26,978  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:17:27,376  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:18:03,856  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:18:03,861  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:18:03,862  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:18:03,868  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:18:12,971  In twitter.py:175: ant deb
ERROR:2015-10-12 11:18:51,165  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 11:18:55,195  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:18:55,197  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:18:55,198  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:18:55,200  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:19:05,326  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:19:05,329  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:19:05,331  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:19:05,333  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:19:11,083  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:19:11,085  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:19:11,086  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:19:11,088  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:19:22,827  In twitter.py:49: Searching for Targets from Twitter Plugin. Search term is : lxtrvn
DEBUG:2015-10-12 11:19:23,344  In twitter.py:55: Twitter returned  1 results
DEBUG:2015-10-12 11:19:23,582  In instagram.py:54: Attempting to search for targets. Search term was : lxtrvn
DEBUG:2015-10-12 11:19:24,097  In instagram.py:73: 1 possible targets were found matching the search query
DEBUG:2015-10-12 11:19:39,963  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:19:39,964  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:19:39,966  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:19:39,968  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:19:39,970  In twitter.py:200: Attempting to retrieve profile information for 421405437
DEBUG:2015-10-12 11:19:40,426  In twitter.py:228: Attempting to retrieve the tweets for user 421405437
DEBUG:2015-10-12 11:19:41,461  In twitter.py:315: 0 locations were retrieved from Twitter Plugin
DEBUG:2015-10-12 11:19:45,374  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:19:45,455  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:19:45,456  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:19:45,458  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 11:20:12,627  In googleplus.py:138: [Errno 2] No such file or directory
DEBUG:2015-10-12 11:20:14,685  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:20:14,686  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:20:14,687  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:20:14,690  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
DEBUG:2015-10-12 11:27:20,662  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:27:20,673  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:27:20,678  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:27:20,711  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .
ERROR:2015-10-12 11:27:51,307  In googleplus.py:138: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 134, in runConfigWizard
    credentials = flow.step2_exchange(str(self.wizard.field('inputCode').toString()).strip(), self.http)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 2131, in step2_exchange
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 507, in __init__
    self._context.load_verify_locations(ca_certs)
IOError: [Errno 2] No such file or directory
DEBUG:2015-10-12 11:27:52,578  In flickr.py:34: Trying to load the labels file for the  flickr plugin .
DEBUG:2015-10-12 11:27:52,579  In instagram.py:32: Trying to load the labels file for the  instagram plugin .
DEBUG:2015-10-12 11:27:52,581  In twitter.py:36: Trying to load the labels file for the  twitter plugin .
DEBUG:2015-10-12 11:27:52,585  In googleplus.py:37: Trying to load the labels file for the  googleplus plugin .

**Comment by lxtrvn** [comment]
This is the problem? 
-------------------------
Traceback (most recent call last):
  File "/root/creepy/creepy/plugins/googleplus/googleplus.py", line 160, in isConfigured
    peopleResource = self.service.people()
AttributeError: 'NoneType' object has no attribute 'people'

**Comment by jkakavas** [comment]
The problem with googleplus plugin is that it expects a cacerts.txt file to be located at the same folder as CreepyMain.py . This was done in order to overcome a limitation in windows installation where httplib2 and urllib3 could not locate the cacerts.txt file so I needed to state that explicitly. Try finding the one that httplib2 comes with 
```
find ~/ -iname 'cacerts.txt'
``` 
and copy that to the folder where CreepyMain.py is.

Alternatively edit googleplus.py and replace line 34 which now contains
```
self.http = httplib2.Http(ca_certs=os.path.join(os.getcwd(), 'cacerts.txt'))
```
with
```
self.http = httplib2.Http()
```

Let me know if that helps

**Comment by lxtrvn** [comment]
I had to use find on / not ~/ so i could get file.    
find / -iname 'cacerts.txt'   
 but copying it over to where CreepyMain.py is solved it. thanks !!!!
