### ISSUE TITLE
help

### ISSUE THREAD

**Issue by krlosclaudia** [jkakavas/creepy#23]
Hey there
I'm from chile and get this software to search for a person trying to hurt my sister hecer on twitter, I want to know from where you write to denounce and sotfware gives me this error when trying seeksTignacioBM

DEBUG: 12/25/2015 18: 51: 47.292 In twitter.py:56: Searching for Targets from Twitter Plugin. Search term is:TignacioBM
ERROR: 12/25/2015 18: 51: 49.831 In twitter.py:79: Error authenticating with Twitter API.
ERROR: 12/25/2015 18: 51: 49.832 In twitter.py:80: [{u'message ': u'Your credentials do not allow access to this resource' u'code ': 220}]
Traceback (most recent call last):
   File "components \ PersonProjectWizard.pyc", line 102, in searchForTargets

I need your help

thanks

**Comment by petterreinholdtsen** [comment]
My guess would be that your Twitter plugin is not configured.  You need a Twitter user and to use the "wizard" in the plugin configuration menu to log in and get a access code for Twitter.

**Comment by jkakavas** [comment]
Check the plugin configuration http://www.geocreepy.com/plugin_configuration.html. You need to configure each plugin you want to use. Closing for now, if the OP comes back, I will reopen it.
