### ISSUE TITLE
Flickr plugin lack getRateLimitStatus()

### ISSUE THREAD

**Issue by petterreinholdtsen** [jkakavas/creepy#29]
When trying to check the rate limit status for the Flickr plugin, I get an AttributionError: 'Instagram' object has no attribute getRateLimitStatus.

I suspect the cause is the line "hasRateLimitInfo = True" which should read "hasRateLimitInfo = False",
but wonder if perhaps you forgot to commit a function to the plugin.

**Comment by jkakavas** [comment]
hasRateLimitInfo is False 
https://github.com/jkakavas/creepy/blob/master/creepy/plugins/flickr/flickr.py#L31

Are you by any change talking about another plugin ? Anyhow, 1257d7ebfa17e776d12df2750cfac63c540c2a31 should take care of this so I am closing the issue

**Comment by petterreinholdtsen** [comment]
[Ioannis Kakavas]
> hasRateLimitInfo is False 
> https://github.com/jkakavas/creepy/blob/master/creepy/plugins/flickr/flickr.py#L31
>
> Are you by any change talking about another plugin ? Anyhow,
> 1257d7ebfa17e776d12df2750cfac63c540c2a31 should take care of this so I
> am closing the issue

Yes, I had another look, and suspect I really ment the Instagram plugin.
It is the only one besides the Twitter plugin with
hasRateLimitInfo=True.  Sorry for the confusion.

-- 
Happy hacking
Petter Reinholdtsen
