### ISSUE TITLE
Missing library dominate on ArchLinux

### ISSUE THREAD

**Issue by DarkRedman** [jkakavas/creepy#3]
I've tried to started it but unfortunately I get this error `ImportError: No module named dominate` I've tried to find it searching *python2 dominate* in **yaourt** but unfortunately there is no match.

**Comment by jkakavas** [comment]
Hi, this is not an issue of creepy, but I ll leave it here. 
dominate is https://github.com/Knio/dominate 

Also you could check the answer I gave to #4 a couple of hours back, You should get pip to work in ArchLinux too.
