### ISSUE TITLE
Port code to python 3?

### ISSUE THREAD

**Issue by petterreinholdtsen** [jkakavas/creepy#32]
Do you have any plans to port the code to python 3?

**Comment by jkakavas** [comment]
Nope, I don't see me making time to do this anytime soon.

**Comment by petterreinholdtsen** [comment]
[Ioannis Kakavas]
> Nope, I don't see me making time to do this anytime soon.

Right.  Thank you for the clear answer.

I believe I saw some plans from the Python team to get rid of python 2
in Debian before the next release, which is expected to freeze in a year
or so, so I guess this might cause Creepy to not be included in the next
stable Debian release.

Perhaps someone find time to provide the patches for Creepy to work with
Python 3 before it is too late. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jkakavas** [comment]
Well, if the time-frame is a year and the stakes are high, I'll keep it in
mind. Thanks for the heads up
