### ISSUE TITLE
unable to configure the plugins

### ISSUE THREAD

**Issue by dasdebajyoti20** [jkakavas/creepy#35]
dear sir,

this the error message  that i am getting whilw trying to configure the plugins:

No handlers could be found for logger "yapsy"
ERROR:2016-01-18 13:07:31,547  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 13:07:31,548  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'

please advice what to do

**Comment by jkakavas** [comment]
Hi, 
Which OS ? 
Also, please explain exactly what you you are trying to do, exactly what errors you get ( the whole log ) and what is the outcome. Is the plugin configured or not ? 
```
ERROR:2016-01-18 13:07:31,547 In googleplus.py:43: Could not load the labels file for the googleplus plugin .
ERROR:2016-01-18 13:07:31,548 In googleplus.py:44: 'labels'
Traceback (most recent call last):
```
This is a strange, but not critical, error. Should not cause you any more problems.

```
File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'
```
This only happens when you click the "Get Rate Limit Info" button in Instagram plugin so again, this would not disallow you from running the wizard.

**Comment by dasdebajyoti20** [comment]
i am using kali 2.0, this what i get in the log when i try to configure the plugins:

No handlers could be found for logger "yapsy"
ERROR:2016-01-18 14:34:13,094  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:13,095  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'
ERROR:2016-01-18 14:34:21,862  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:21,863  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'
ERROR:2016-01-18 14:34:29,122  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:29,122  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'

**Comment by jkakavas** [comment]
What about the UI ? Is the plugin configured after all ?in which part of the process do you get the error ? 
Please help me to help you, I won't have the time to get the info from you bit by bit :)

Do you use the version that comes with Kali or did you get the source code from here ? 

Kali comes with cree,py 1.0 as far as I know ,and you should be better off following the instructions in http://www.geocreepy.com/ on how to get it working there with v1.4

**Comment by dasdebajyoti20** [comment]
the default version of creepy in kali 2.0, that is creepy v1.0, it was not working, there also the plugin window was empty, i tried upgrading the applications in my kali using 'apt-get safe-upgrade' it didn't work.

so following the instructions given on the page 'www.geocreepy.com' i got creepy v1.4 and tried running, it ran, but i am unable to configure the plugins, that is when i got the error message i posted in my last message.

note: i am relatively new in all this so have limited idea.

please advice

**Comment by dasdebajyoti20** [comment]
just after opening creepy v 1.4 i went to the 'plugin configuration tab' i clicked it and other than getting the plugin window i got the error message in the log window. which in have posted in my previous comment yet for ur convenience i will post here again:


No handlers could be found for logger "yapsy"
ERROR:2016-01-18 14:34:13,094  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:13,095  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'
ERROR:2016-01-18 14:34:21,862  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:21,863  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'
ERROR:2016-01-18 14:34:29,122  In googleplus.py:43: Could not load the labels file for the  googleplus plugin .
ERROR:2016-01-18 14:34:29,122  In googleplus.py:44: 'labels'
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'

**Comment by jkakavas** [comment]
Click on the configuration wizard for each plugin you want to configure. So far I didn't see anything that would block you from doing so., Check the instructions at http://www.geocreepy.com/plugin_configuration.html

**Comment by dasdebajyoti20** [comment]
sir, 
whenever i am clicking on the 'config. wizard' i am getting the mentioned error, i am not getting the window. shown in the instructions.

**Comment by jkakavas** [comment]
Download the source code from https://github.com/jkakavas/creepy/archive/master.zip , we have made some modifications lately. Tell me if that works

**Comment by dasdebajyoti20** [comment]
sir, 
i just ran the above mentioned version, i opened creepy and clicked on  the 'config. wizard' this was what came in the ' log output':

No handlers could be found for logger "yapsy"
Traceback (most recent call last):
  File "CreepyMain.py", line 716, in showPluginsConfigurationDialog
    if not plugin.plugin_object.hasRateLimitInfo:
AttributeError: 'Instagram' object has no attribute 'hasRateLimitInfo'

**Comment by dasdebajyoti20** [comment]
dear sir,

i repeated the whole process again, as was mentioned in the instructions and ran the updated source code, and now it is working fine!!

i would like to thank you for your time and patience.
