### ISSUE TITLE
Search through the "from:"

### ISSUE THREAD

**Issue by Simiae** [jkakavas/creepy#36]
With time, I realized that the older tweets were disappearing, and the only way to search them was typing "from: USERNAME". Have some form of search with cree.py using the "from:"?

**Comment by jkakavas** [comment]
Sorry, I don't really get what you are saying. 
> older tweets were disappearing,
from where 

> the only way to search them was typing "from: USERNAME"
in what ?

**Comment by Simiae** [comment]
I'm sorry, my english skills are bad. I was wondering if there's a way of scanning with the command of the twitter "from:". If you put in search box of the twitter the command, ex: "from:cree.py", you can see ALL the tweets of the person, I was wondering if there is a way to search with this command in cree.py.

Over time, the old tweets from some people will disappearing. I do not know why it happens, and just typing on twitter search box the command "from: USERNAME" you can see all the person's tweets. So I wonder if the cree.py can scan with this command.

**Comment by jkakavas** [comment]
No, there is no equivalent. You can run the analysis multiple times in case the first time only fetched few (or fewer than you expected ) results.
