### ISSUE TITLE
Issues getting Creepy to work under Ubuntu 14.04.2

### ISSUE THREAD

**Issue by OpenFerret** [jkakavas/creepy#4]
When I try to exeute:  
user@ubuntu:~/Downloads/creepy-master/creepy$ sudo python CreepyMain.py

I get:  
Traceback (most recent call last):
  File "CreepyMain.py", line 11, in <module>
    import pytz
ImportError: No module named pytz

Is there a .deb package coming any time?  Many thanks for you time!

**Comment by OpenFerret** [comment]
Sorry, bit of google and I found I was missing the python-tz package... But now If hit my next error:
user@ubuntu:~/Downloads/creepy-master/creepy$ python CreepyMain.py
Traceback (most recent call last):
  File "CreepyMain.py", line 18, in <module>
    from dominate import document
ImportError: No module named dominate

**Comment by jkakavas** [comment]
You would be better off installing the necessary python modules from pip, instead of the system packages. First get pip and the pyqt4 bindings from ubuntu repositories
```$ sudo apt-get install python-pip python-qt4```

Then you can get all the necessary packages with 
```$ sudo pip install dominate pytz yapsy tweepy flickrapi python-instagram google-api-python-client configobj python-dateutil```

**Comment by OpenFerret** [comment]
Excellent, thank you.  Up and running now.
