### ISSUE TITLE
Instagram plugin error

### ISSUE THREAD

**Issue by Lasroad** [jkakavas/creepy#41]
Got a error ' Please verify that the link you pasted was correct. Try running the wizard again.' when running the instagram plugin wizard ,the link i copied was correct but still get error after i paste the token value ,tried several times still get the same error. I am using kali linux rolling 2016 and the latest version on creepy .Please help

**Comment by jkakavas** [comment]
In Kali Linux 2016.1 : 

`apt-get remove --purge creepy`
`git clone https://github.com/jkakavas/creepy.git `

Then go into the creepy folder and run python CreepyMain.py, it should work fine. 

This will have to do until I find time to work with the debian package, sorry for the inconvenience.
