### ISSUE TITLE
Instagram Plugin link not working

### ISSUE THREAD

**Issue by jckzw** [jkakavas/creepy#47]
{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}

Is the error I get when click "Open in browser" or when I copy the link into the browser directly. Tried logging in and out of instagram and same error. 

Using Windows 7

**Comment by n0h3ad2016** [comment]
same error! help!

**Comment by uptospeed99** [comment]
Error:
{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}

Instagram updated their API terms on June 1st, which places all apps in "Sandbox Mode" until the developers submit their apps for "Live Mode". Developers must fix. Nothing users can do.

https://www.instagram.com/developer/sandbox/

**Comment by glerinsonum** [comment]
## **Error getting access token**

**Comment by jkakavas** [comment]
Closing this, progress is tracked on #49
