### ISSUE TITLE
No locations found

### ISSUE THREAD

**Issue by aceyagami** [jkakavas/creepy#48]
Hello. I tried with my own twitter account and others, but always shows this error.

"We could not find any locations for the analyzed project"

Is there any solution?

![captura](https://cloud.githubusercontent.com/assets/19965750/16104163/68c2a43a-3344-11e6-863f-56ec8bd8df3c.png)

**Comment by jkakavas** [comment]
This is not a problem or a bug. The accounts you search for haven't publish any geotagged tweets
