### ISSUE TITLE
Startup error (invalid syntax)

### ISSUE THREAD

**Issue by SurPaul** [jkakavas/creepy#56]
I can't open Creepy. I installed all dependencies. Help me, please

```
File "./CreepyMain.py", line 217
    except Exception, err:
                    ^
SyntaxError: invalid syntax
```
![2017-03-14 16-58-27](https://cloud.githubusercontent.com/assets/1708881/23901627/889a8a8e-08d7-11e7-9269-196ad89a314c.png)

**Comment by jkakavas** [comment]
creepy is written for Python2 and you are using python3. There are some
subtle changes between versions. Please use python 2.7 for now , until
creepy is made compatible with both
