### ISSUE TITLE
configuration wizard does not work

### ISSUE THREAD

**Issue by beren74** [jkakavas/creepy#6]
Seems that on the latest version 1.3 the configuration wizard does now work.
 I run  the wizard even putting my twitter nick and on search results appear nothing.
I am working under windos 7 os.

**Comment by jkakavas** [comment]
You are mixing things up and I Can't understand what you are trying to say. The way you talk about the plugin configuration wizard makes me think that you actually talk about the new project wizard. 
You need to configure the twitter plugin first before using it in a project.

**Comment by beren74** [comment]
![osint](https://cloud.githubusercontent.com/assets/6661496/7265909/f0957444-e8a1-11e4-914e-37d35ab2fd90.png)

if you look at the screenshot explain it all
if I run my name on search or any other name, nothing happens. Search results=0
is it clear now?
Thanks

**Comment by jkakavas** [comment]
This is not the configuration wizard,that's the new project wizard. I
repeat that you have to configure the plug-ins before tou use them.

Use the appropriately named "plugin configuration " for that.

**Comment by beren74** [comment]
Ok I do configure the plug in?

**Comment by jkakavas** [comment]
Yes, you need to configure the plugin.

2015-04-22 15:23 GMT+03:00 beren74 <notifications@github.com>:

**Comment by beren74** [comment]
ok got it. Previous versions did not have it, so I was a little confused
