### ISSUE TITLE
-Phone number search?-

### ISSUE THREAD

**Issue by class06408** [jkakavas/creepy#60]
ok so I noticed this awesome project is on GitHub and I am thrilled...  One suggestion/bug/Problem, is not being able to search with a phone number "specifically".  could help find locations.  theory:  telephone search = phone number + ping?
phone number = 'number'
ping = ping duh! lol... 

the way I see it... if you can ping a number on a phone you might be able to see how far it is.  by distance/formula for ping(mathematics) maybe adding a search function should be new way to search!!

**Comment by class06408** [comment]
-However... if you Can search with a phone number than please add it to the dialog box that states what to add to the search or how... ty!

**Comment by jkakavas** [comment]
There is no way to do what you are asking.

**Comment by class06408** [comment]
Hello Mr.Cree.py,  I am happy you replied to the thread on Github.  It was
a good thought, wish it was possible.  im gonna take another go at
experimenting with the application it is truly inspiring.  Ty again!
